services:
  - type: web
    name: email-scraper
    runtime: python
    buildCommand: ./setup.sh
    startCommand: streamlit run app.py --server.port $PORT
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: "1"
    plan: free
